# -*- coding: utf-8 -*-
"""One-shot Hinglish -> English pass over the backend sources (batch 3)."""
import io
import sys

PATCHES = {}


def P(path, old, new):
    PATCHES.setdefault(path, []).append((old, new))


D = "—"  # em dash used throughout the sources
Q = "’"  # right single quote


# ----------------------------------------------------- app/conversations.py
P("app/conversations.py",
'''"""Conversations list karna, kholna aur delete karna.

**Ye ek asli bug theek karta hai, feature nahi jodta.** Conversation memory Phase 4
me bani aur kaam bhi karti thi @ par UI har page load pe naya `thread_id` banata
tha. Matlab har purani conversation Postgres me **padi rehti thi aur pahunch se
bahar ho jaati thi**. Data delete nahi ho raha tha, orphan ho raha tha. Bahar se
"refresh pe sab gayab" dikhta tha; andar se ye ek memory feature tha jo apne hi
checkpoints kabhi dobara nahi dhoondhta tha.

**Do alag raaste, jaan-boojh ke:**

- **Thread list SQL se** @ `checkpoints` table se sirf `thread_id` aur timestamp.
  Sasta hai aur koi deserialization nahi.
- **Har thread ka content checkpointer ke API se** @ pehla version blobs ko
  seedha SQL se padhne ki koshish karta tha, aur wo **galat approach thi**:
  LangGraph channel values ko `checkpoint_blobs` me **msgpack** me rakhta hai,
  jsonb me nahi. Use haath se decode karna ek andaruni format ko copy karna hota,
  jo agli library release me chup-chaap toot jaata. Checkpointer khud jaanta hai
  ki usne kya likha tha @ usi se poochhna chahiye.
"""''',
'''"""Listing, opening and deleting conversations.

**This fixes a real bug rather than adding a feature.** Conversation memory was
built in Phase 4 and did work @ but the UI generated a fresh `thread_id` on every
page load. That meant every previous conversation **stayed in Postgres and became
unreachable**. The data was not being deleted, it was being orphaned. From
outside it looked like "everything disappears on refresh"; from inside it was a
memory feature that never looked up its own checkpoints again.

**Two different routes, deliberately:**

- **The thread list comes from SQL** @ only `thread_id` and a timestamp out of the
  `checkpoints` table. Cheap, and no deserialization.
- **Each thread’s content comes from the checkpointer’s own API** @ the first
  version tried to read the blobs directly with SQL, and that was **the wrong
  approach**: LangGraph stores channel values in `checkpoint_blobs` as **msgpack**,
  not jsonb. Decoding it by hand would mean copying an internal format that would
  break silently on the next library release. The checkpointer knows what it
  wrote @ so it is the thing to ask.
"""''')

P("app/conversations.py",
'''    """Checkpointer kabhi chala hi na ho to `checkpoints` table hoti hi nahi."""''',
'''    """If the checkpointer never ran, the `checkpoints` table does not exist."""''')

P("app/conversations.py",
'''    """Thread ids, sabse haal wali pehle.

    `checkpoint->>\\'ts\\'` par sort karte hain, `thread_id` par nahi. Thread id me
    timestamp hota to hai, par wo **client banata hai** @ ek alag client alag
    format bhej de to ordering chup-chaap galat ho jaati. `ts` server ka likha
    hua hai.
    """''',
'''    """Thread ids, most recent first.

    Sorted on the checkpoint timestamp, not on `thread_id`. The thread id does
    contain a timestamp, but it is **generated by the client** @ a different
    client sending a different format would silently break the ordering. The
    timestamp is written by the server.
    """''')

P("app/conversations.py",
'''    """Ek thread ki history, checkpointer ke apne deserializer se."""''',
'''    """One thread’s history, via the checkpointer’s own deserializer."""''')

P("app/conversations.py",
'''    """Saved conversations, naya pehle.

    Har thread ka ek checkpoint read hota hai @ 40 threads pe 40 chhote reads.
    Ek sidebar ke liye theek hai; hazaaron conversations par ye ek alag summary
    table maangta, kyunki tab har page load pe poori list deserialize karna bewajah
    ka kharcha ban jaata.
    """''',
'''    """Saved conversations, newest first.

    One checkpoint read per thread @ 40 threads means 40 small reads. That is fine
    for a sidebar; at thousands of conversations it would call for a separate
    summary table, because deserializing the whole list on every page load would
    become needless cost.
    """''')

P("app/conversations.py",
'''            # Ek thread jisme koi poora turn nahi hua @ user ne kuch poocha aur
            # jawab aane se pehle chala gaya. Ise list me dikhana matlab ek aisi
            # conversation offer karna jisme kuch hai hi nahi.''',
'''            # A thread with no completed turn @ the user asked something and left
            # before the answer arrived. Listing it would mean offering a
            # conversation that has nothing in it.''')

P("app/conversations.py",
'''    """Ek conversation ke saare turns @ reload ke baad transcript dobara banane ke liye."""''',
'''    """Every turn of one conversation @ to rebuild the transcript after a reload."""''')

P("app/conversations.py",
'''    """Ek conversation ke saare checkpoints hata deta hai.

    Teeno tables se hataana padta hai @ sirf `checkpoints` saaf karne se
    `checkpoint_writes` aur `checkpoint_blobs` me orphan rows reh jaati hain, aur
    wahi haalat dobara ban jaati hai jo is file ne theek ki: data jo maujood hai
    par pahunch se bahar.
    """''',
'''    """Delete every checkpoint belonging to one conversation.

    All three tables have to be cleared @ removing only `checkpoints` leaves
    orphaned rows in `checkpoint_writes` and `checkpoint_blobs`, recreating
    exactly the situation this file was written to fix: data that exists but
    cannot be reached.
    """''')


# -------------------------------------------------------------- app/seed.py
P("app/seed.py",
'''"""Realistic seed data @ deterministically generated.

**Kyun 10 rows kaafi nahi the.** Purana dataset 10 employees aur 4 departments ka
tha, aur usse teen cheezein toot rahi thi:

- **Dashboard khaali dikhta tha.** Chaar bars ka bar chart chart nahi lagta.
- **Koi date column hi nahi tha**, matlab "hiring trend" jaisa sabse natural
  dashboard sawaal poochha hi nahi ja sakta tha.
- **Joins do table se aage nahi jaate the.** Real Text-to-SQL ki dikkat multi-hop
  join me hai @ "kis project pe sabse mehnge log lage hain" jaisa sawaal teen
  tables chhoota hai, aur wahi jagah hai jahan model galtiyan karta hai.

**Random hai, par seeded random hai.** `random.Random(42)` fixed hai, to har
machine par bilkul wahi data banta hai. Ye eval ke liye zaroori hai: agar seed
badalta rehta to accuracy ka har number pichhle run se compare karne layak hi na
rehta, aur "self-healing se accuracy badhi" jaisa daawa bemaani ho jaata.
"""''',
'''"""Realistic seed data @ deterministically generated.

**Why 10 rows were not enough.** The old dataset had 10 employees and 4
departments, and three things broke because of it:

- **The dashboard looked empty.** A bar chart with four bars does not read as a
  chart.
- **There was no date column at all**, so the most natural dashboard question of
  all @ "hiring trend" @ could not even be asked.
- **Joins never went past two tables.** The hard part of real Text-to-SQL is the
  multi-hop join @ a question like "which project has the most expensive people
  on it" touches three tables, and that is exactly where models make mistakes.

**It is random, but seeded random.** `random.Random(42)` is fixed, so every
machine generates exactly the same data. That matters for the eval: if the seed
drifted, no accuracy number could be compared with a previous run, and a claim
like "self-healing improved accuracy" would mean nothing.
"""''')

P("app/seed.py",
'''# Fixed seed. Isko badalna matlab har purana eval number bekaar ho jaana.''',
'''# Fixed seed. Changing it invalidates every previous eval number.''')

P("app/seed.py",
'''# Har department ke roles, salary band ke saath. Bands overlap karte hain aur
# seniority ke saath badhte hain @ flat random salary se questions bemaani ho
# jaate ("highest paid" ka jawab shudh sanyog hota).''',
'''# Roles per department, with a salary band. The bands overlap and rise with
# seniority @ a flat random salary would make the questions meaningless ("highest
# paid" would be pure coincidence).''')

P("app/seed.py",
'''# Headcount har department ka. Jaan-boojh ke asamaan: Engineering bada, HR chhota
# @ taaki "which department has the most people" ka jawab dilchasp ho, sabka
# ek jaisa na ho.''',
'''# Headcount per department. Deliberately uneven: Engineering large, HR small @ so
# that "which department has the most people" has an interesting answer rather
# than a tie.''')

P("app/seed.py",
'''    """Unique naam. Duplicates se "who earns most" jaise sawaal ambiguous ho jaate."""''',
'''    """A unique name. Duplicates would make questions like "who earns most" ambiguous."""''')

P("app/seed.py",
'''    # Naam khatam ho jaayein to suffix @ chup-chaap duplicate dene se behtar.''',
'''    # If the names run out, add a suffix @ better than silently returning a duplicate.''')

P("app/seed.py",
'''            # Manager-level roles kam hote hain: aakhri role har department me
            # senior hai, aur wo sirf 10% logon ko milta hai. Isse "average
            # salary" aur "highest paid" alag jawab dete hain, jo unhe interesting
            # banata hai.''',
'''            # Manager-level roles are rare: the last role in each department is
            # the senior one, and only 10% of people get it. That makes "average
            # salary" and "highest paid" give different answers, which is what
            # makes them interesting questions.''')

P("app/seed.py",
'''            # Hire dates pichhle ~6 saal me faili hui, haal ke saalon me zyada @
            # ek badhti hui company jaisa. Iske bina hiring-trend chart flat aata.
            #
            # `abs(gauss)` zyadatar 0-3 ke beech rehta hai, isliye multiplier hi
            # asli spread tay karta hai: 700 se lagbhag 6 saal milte hain. Pehla
            # version 380 tha aur sirf 3 saal deta tha @ comment 6 kehta tha,
            # data 3 dikhata tha.''',
'''            # Hire dates spread over roughly the last 6 years, weighted towards
            # recent ones @ the shape of a growing company. Without that, the
            # hiring-trend chart comes out flat.
            #
            # `abs(gauss)` mostly lands between 0 and 3, so the multiplier is what
            # actually sets the spread: 700 gives about 6 years. The first version
            # used 380 and only produced 3 @ the comment said 6 while the data
            # showed 3.''')

P("app/seed.py",
'''    """(name, department, start_date, status) @ teesri table, multi-hop joins ke liye."""''',
'''    """(name, department, start_date, status) @ the third table, for multi-hop joins."""''')


# -------------------------------------------------------- mcp_server/server.py
P("mcp_server/server.py",
'''"""MCP server jo is project ka database tools ke roop me expose karta hai.

**Ye alag process me chalta hai**, agent ke saath stdio pipe se baat karta hai.
Isi baat ka poora point hai: data access ab agent ke andar `import` ki hui cheez
nahi, ek **protocol ke peeche baithi hui service** hai. Usi agent ko kal kisi aur
MCP server se joda ja sakta hai @ GitHub, filesystem, kisi doosre database @ bina
agent ka ek line badle. Aur ye server bhi kisi doosre MCP client (Claude Desktop,
koi IDE) se use ho sakta hai, kyunki interface standard hai, hamara khud ka
banaya hua nahi.

Chalane ke liye:  python -m mcp_server.server
Agent ise khud subprocess ki tarah start karta hai @ dekho `app/mcp_client.py`.
"""''',
'''"""An MCP server exposing this project’s database as tools.

**It runs in its own process** and talks to the agent over a stdio pipe. That is
the entire point: data access is no longer something the agent `import`s, it is a
**service behind a protocol**. The same agent could be pointed at a different MCP
server tomorrow @ GitHub, a filesystem, another database @ without changing a
line of the agent. And this server can equally be used by any other MCP client
(Claude Desktop, an IDE), because the interface is a standard one rather than
something we invented.

To run it:  python -m mcp_server.server
The agent starts it as a subprocess itself @ see `app/mcp_client.py`.
"""''')

P("mcp_server/server.py",
'''# MCP SDK 2.x me `FastMCP` ka naam `MCPServer` ho gaya. Ye pehli koshish me toota
# tha, aur wo failure achhi tarah dikhi: client ne fallback lete hue direct
# driver use kar liya aur wajah log kar di @ bilkul waisa hi jaisa design kiya
# tha. Ek chup-chaap fail hone wala MCP path sabse kharaab nateeja hota.''',
'''# MCP SDK 2.x renamed `FastMCP` to `MCPServer`. This broke on the first attempt,
# and the failure showed up well: the client fell back to the direct driver and
# logged the reason @ exactly as designed. An MCP path that failed silently would
# have been the worst outcome.''')


# ------------------------------------------------------------------- apply
def main():
    missing = 0
    for path, pairs in sorted(PATCHES.items()):
        src = io.open(path, encoding="utf-8").read()
        for old, new in pairs:
            needle = old.replace("@", D)
            if needle not in src:
                print("MISS  %s :: %s" % (path, needle.strip().splitlines()[0][:70]))
                missing += 1
                continue
            src = src.replace(needle, new.replace("@", D), 1)
        io.open(path, "w", encoding="utf-8", newline="\n").write(src)
        print("wrote %s" % path)

    print("missing blocks: %d" % missing)
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
