"""Listing, opening and deleting conversations.

**This fixes a real bug rather than adding a feature.** Conversation memory was
built in Phase 4 and did work — but the UI generated a fresh `thread_id` on every
page load. That meant every previous conversation **stayed in Postgres and became
unreachable**. The data was not being deleted, it was being orphaned. From
outside it looked like "everything disappears on refresh"; from inside it was a
memory feature that never looked up its own checkpoints again.

**Two different routes, deliberately:**

- **The thread list comes from SQL** — only `thread_id` and a timestamp out of the
  `checkpoints` table. Cheap, and no deserialization.
- **Each thread’s content comes from the checkpointer’s own API** — the first
  version tried to read the blobs directly with SQL, and that was **the wrong
  approach**: LangGraph stores channel values in `checkpoint_blobs` as **msgpack**,
  not jsonb. Decoding it by hand would mean copying an internal format that would
  break silently on the next library release. The checkpointer knows what it
  wrote — so it is the thing to ask.
"""

from __future__ import annotations

import logging
from typing import Optional

from sqlalchemy import text

from app.checkpointer import get_checkpointer
from app.db import engine

log = logging.getLogger(__name__)

MAX_CONVERSATIONS = 40


def _tables_exist(conn) -> bool:
    """If the checkpointer never ran, the `checkpoints` table does not exist."""
    return bool(conn.execute(text("SELECT to_regclass('public.checkpoints')")).scalar())


def _thread_ids(limit: int) -> list[str]:
    """Thread ids, most recent first.

    Sorted on the checkpoint timestamp, not on `thread_id`. The thread id does
    contain a timestamp, but it is **generated by the client**, and a different
    client sending a different format would silently break the ordering. The
    checkpoint timestamp is written by the server.
    """
    try:
        with engine.connect() as conn:
            if not _tables_exist(conn):
                return []
            rows = conn.execute(
                text(
                    "SELECT thread_id, MAX(checkpoint->>'ts') AS ts "
                    "FROM checkpoints GROUP BY thread_id "
                    "ORDER BY ts DESC LIMIT :limit"
                ),
                {"limit": limit},
            ).fetchall()
        return [r[0] for r in rows]
    except Exception as exc:  # noqa: BLE001 — DB down; sidebar degrades, app lives
        log.warning("Could not list conversation threads (%s).", exc)
        return []


def _history(thread_id: str) -> list:
    """One thread’s history, via the checkpointer’s own deserializer."""
    saver = get_checkpointer()
    if saver is None:
        return []
    try:
        tup = saver.get_tuple({"configurable": {"thread_id": thread_id}})
    except Exception as exc:  # noqa: BLE001 — one unreadable thread must not kill the list
        log.warning("Could not read conversation %s (%s).", thread_id, exc)
        return []

    if tup is None:
        return []
    history = (tup.checkpoint or {}).get("channel_values", {}).get("history")
    return history if isinstance(history, list) else []


def list_conversations(limit: int = MAX_CONVERSATIONS) -> list[dict]:
    """Saved conversations, newest first.

    One checkpoint read per thread — 40 threads means 40 small reads. That is fine
    for a sidebar; at thousands of conversations it would call for a separate
    summary table, because deserializing the whole list on every page load would
    become needless cost.
    """
    conversations = []
    for thread_id in _thread_ids(limit):
        history = _history(thread_id)
        if not history:
            # A thread with no completed turn — the user asked something and left
            # before the answer arrived. Listing it would mean offering a
            # conversation that has nothing in it.
            continue
        conversations.append(
            {
                "thread_id": thread_id,
                "title": (history[0].get("question") or "Untitled")[:80],
                "turns": len(history),
            }
        )
    return conversations


def get_conversation(thread_id: str) -> Optional[dict]:
    """Every turn of one conversation — to rebuild the transcript after a reload."""
    history = _history(thread_id)
    if not history:
        return None
    return {"thread_id": thread_id, "turns": history}


def delete_conversation(thread_id: str) -> bool:
    """Delete every checkpoint belonging to one conversation.

    All three tables have to be cleared — removing only `checkpoints` leaves
    orphaned rows in `checkpoint_writes` and `checkpoint_blobs`, recreating
    exactly the situation this file was written to fix: data that exists but
    cannot be reached.
    """
    try:
        with engine.begin() as conn:
            if not _tables_exist(conn):
                return False
            for table in ("checkpoint_writes", "checkpoint_blobs", "checkpoints"):
                conn.execute(
                    text(f"DELETE FROM {table} WHERE thread_id = :tid"),  # noqa: S608
                    {"tid": thread_id},
                )
        return True
    except Exception as exc:  # noqa: BLE001
        log.warning("Could not delete conversation %s (%s).", thread_id, exc)
        return False
