"""Request and response shapes for the API.

Kept apart from the routers because these are the contract — the thing a client
depends on — while the routers are just wiring. Several fields here exist to
report something the caller could otherwise only guess at, and each carries the
reason in its docstring: `awaiting_approval`, `memory_active` and
`guardrail_flags` all describe state that would be invisible and misleading if
inferred from an empty answer.
"""

from pydantic import BaseModel


class QueryRequest(BaseModel):
    question: str
    thread_id: str | None = None
    """Conversation id. Send one and the agent remembers the previous turns.

    Generated by the client, not the server — a server-generated session id would
    mean cookies and session state, which is needless weight in a stateless API.
    Without a `thread_id` the API behaves exactly as it did before, statelessly,
    so older clients keep working unchanged.
    """


class ApprovalRequest(BaseModel):
    thread_id: str
    approved: bool
    """The human decision. `thread_id` is not optional here.

    An approval always belongs to a paused conversation, and that conversation can
    only be found in the checkpointer by its `thread_id` — without it there is
    nothing to approve.
    """


class QueryResponse(BaseModel):
    question: str
    sql_query: str
    final_answer: str
    logs: list[str]
    retry_count: int
    thread_id: str | None = None
    awaiting_approval: bool = False
    """The graph is paused on a destructive query, waiting for a human decision.

    When this is `true`, `final_answer` is empty and `sql_query` holds the
    statement awaiting approval. The client has to call `/api/approve` — until
    then the turn is not finished. This had to be its own flag: an empty
    `final_answer` on its own reads as "nothing was found", when in fact the
    system is asking the user a question.
    """
    result_rows: list[dict] = []
    """The query rows, for the table (up to 50)."""

    row_count: int = 0

    guardrail_flags: list[str] = []
    """What the output guard caught. Empty means nothing was found."""

    memory_active: bool = False
    """Whether conversation memory actually ran on this turn.

    Sending a `thread_id` does not mean memory was used — checkpointer setup can
    fail (DB down, permissions) and the agent then carries on statelessly. That
    fallback is deliberate, but it must not be **hidden**: the UI needs to know
    whether a follow-up will work, or the user will think the agent forgot when in
    fact memory was never on.
    """


class DashboardRequest(BaseModel):
    request: str
    thread_id: str | None = None
